/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-tint": "#5e5e5e",
        "surface-container-highest": "#e2e2e4",
        "on-background": "#1a1c1d",
        "surface-container-low": "#f3f3f5",
        "background": "#f9f9fb",
        "on-secondary-fixed": "#1b1b1b",
        "on-error": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-fixed-variant": "#3b3b3b",
        "on-surface-variant": "#474747",
        "outline-variant": "#c6c6c6",
        "surface-container-high": "#e8e8ea",
        "on-secondary-container": "#1b1b1b",
        "on-primary": "#e2e2e2",
        "surface-container": "#eeeef0",
        "secondary": "#5e5e5e",
        "on-tertiary-container": "#ffffff",
        "on-surface": "#1a1c1d",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ababab",
        "primary": "#000000",
        "primary-fixed-dim": "#474747",
        "tertiary": "#3b3b3b",
        "on-secondary": "#ffffff",
        "on-tertiary": "#e2e2e2",
        "outline": "#777777",
        "secondary-container": "#d4d4d4",
        "tertiary-container": "#747474",
        "on-error-container": "#410002",
        "tertiary-fixed": "#5e5e5e",
        "inverse-surface": "#2f3132",
        "primary-fixed": "#5e5e5e",
        "on-primary-container": "#ffffff",
        "error-container": "#ffdad6",
        "surface-bright": "#f9f9fb",
        "secondary-fixed": "#c6c6c6",
        "on-primary-fixed-variant": "#e2e2e2",
        "tertiary-fixed-dim": "#474747",
        "surface": "#f9f9fb",
        "surface-dim": "#d9dadc",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "primary-container": "#3b3b3b",
        "surface-variant": "#e2e2e4",
        "inverse-primary": "#c6c6c6",
        "inverse-on-surface": "#f0f0f2",
        "on-tertiary-fixed": "#ffffff",
        "on-primary-fixed": "#ffffff",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [require("@tailwindcss/forms"), require("@tailwindcss/container-queries")],
};
